### ISSUE TITLE
I got a problem while running multiple times the python script

### ISSUE THREAD

**Issue by theja0473** [api-ai/api-ai-python#14]
![capture2323](https://cloud.githubusercontent.com/assets/15976291/17478285/5c124b1e-5d88-11e6-9924-cb3f08c0dc98.PNG)

**Comment by sstepashka** [comment]
Hey, i was try to run it multiple time on my machine and it work finally... 

This error exist for raspberri pi in pyaudio: https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=71062
