### ISSUE TITLE
Example code gives json request parse error

### ISSUE THREAD

**Issue by rokusottervanger** [api-ai/api-ai-python#24]
As the old voice_request is marked deprecated, I'm using a text_request to send audio data as instructed [here](https://github.com/api-ai/api-ai-python/blob/master/apiai/requests/query/voice.py#L32), using a wav file (Unsigned 8 bit, or Signed 16 bit Little Endian, Rate 16000 Hz). However, this gives me the following result:
```json
{
  "error": {
    "code": "002",
    "errorId": "ab6473fe-a57a-49ed-8a08-21a58570be78",
    "message": "json request parse error"
  }
}
```
What am I doing wrong?

**Comment by sstepashka** [comment]
Just forgot about voice request. It won't work for you.

**Comment by rokusottervanger** [comment]
The README says it is possible to do speech recognition through this python api. How do I do that then?

**Comment by sstepashka** [comment]
@rokusottervanger No way. This api has been removed.

**Comment by rokusottervanger** [comment]
Apparently, using Google Cloud Speech API is the way to go now. Maybe this should be updated in the documentation...
