### ISSUE TITLE
json.loads error string expected not bytes

### ISSUE THREAD

**Issue by gautamworah96** [api-ai/api-ai-python#28]
When I use the json.loads(request.getresponse().read()) function an error pops up " TypeError: the JSON object must be str, not 'bytes' ".
The response.read() function works well and I get a JSON object printed out with the correct intent and action however json.loads isnt working.
I am using this as a part of a Django application.
Is there any other way to access the attributes of the response?

Thanks ,
Gautam.

Code snippet:
 
        ai = apiai.ApiAI(client_base)
	request = ai.text_request()
	request.session_id = "xxx...xxxx"
	request.query = msg
	response = json.loads(request.getresponse().read())
	#print("now printing response")
	result = response['result']
	action = result.get('action')
	print(action)

Browser Error Snippet:

TypeError at /Main/
the JSON object must be str, not 'bytes'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/Main/
Django Version:	1.10.1
Exception Type:	TypeError
Exception Value:	
the JSON object must be str, not 'bytes'

**Comment by sstepashka** [comment]
Hi @gautamworah96 what version of python you use?

**Comment by gautamworah96** [comment]
3.5.2

**Comment by sstepashka** [comment]
@gautamworah96 
```python
response = json.loads(request.getresponse().read().decode("utf-8"))

```
