### ISSUE TITLE
status code = 200, but no result

### ISSUE THREAD

**Issue by hillerliao** [api-ai/api-ai-python#9]
`{
  "id": "be29b06a-84dc-4e86-99dc-20a0ad49a2e9",
  "timestamp": "2016-04-21T01:10:16.984Z",
  "result": {
    "source": "agent",
    "resolvedQuery": "hello",
    "contexts": [],
    "metadata": {},
    "fulfillment": {
      "speech": ""
    },
    "score": 0
  },
  "status": {
    "code": 200,
    "errorType": "success"
  }
}`

**Comment by hillerliao** [comment]
sorry , fixed.  i did not turn on Domains Knowledge Base (beta)

**Comment by sstepashka** [comment]
okey :)
